version: "3.9"
   
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
      - ./log:/app/log
      - ./log:/var/log/nginx
      - ./log:/var/log/uwsgi/app
      - ./hyper_pets_backend/production/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
      - ./hyper_pets_backend/production/uwsgi.ini:/etc/uwsgi/apps-enabled/uwsgi.ini
      - ./hyper_pets_backend/production/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
    ports:
      - "8000:8000"
    restart: "always"
    command: >
      sh -c "
        # python3 -m pip install -U -r requirements.txt
        python3 manage.py migrate --settings=hyper_pets_backend.production.settings
        # python3 manage.py collectstatic --no-input --settings=hyper_pets_backend.production.settings
        # python3 manage.py uwsgi
        # service supervisor start
        # service nginx start
        python3 manage.py runserver 0.0.0.0:8000 --settings=hyper_pets_backend.production.settings
        tail -f /dev/null"