# Generated by Django 4.2.16 on 2025-02-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Specialties",
            },
        ),
        migrations.AlterField(
            model_name="pet",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="pet",
            name="gender",
            field=models.CharField(choices=[("M", "수컷"), ("F", "암컷")], max_length=1),
        ),
        migrations.AlterField(
            model_name="pet",
            name="shelter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="api.shelter",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="species",
            field=models.CharField(
                choices=[("dog", "강아지"), ("cat", "고양이"), ("other", "기타")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "입양가능"),
                    ("pending", "입양진행중"),
                    ("adopted", "입양완료"),
                ],
                default="available",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="weight",
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name="hospital",
            name="specialties",
            field=models.ManyToManyField(
                blank=True, related_name="hospitals", to="api.specialty"
            ),
        ),
    ]
