# Generated by Django 4.2.19 on 2025-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="social_provider",
            field=models.CharField(
                blank=True,
                help_text="소셜 로그인 제공자 (google, kakao, naver 등)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="social_provider_id",
            field=models.CharField(
                blank=True, help_text="소셜 로그인 제공자의 사용자 ID", max_length=100, null=True
            ),
        ),
    ]
