# Generated by Django 4.2.19 on 2025-03-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_customuser_social_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("parent_code", models.CharField(blank=True, max_length=10, null=True)),
                ("rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_date", models.DateField(blank=True, null=True)),
                ("abolished_date", models.DateField(blank=True, null=True)),
                ("last_updated_date", models.DateField(blank=True, null=True)),
                ("is_lowest_level", models.BooleanField(default=False)),
                (
                    "resident_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "cadastral_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("link", models.URLField(max_length=1000)),
                ("snippet", models.TextField()),
                ("published_date", models.DateTimeField()),
                ("source", models.CharField(max_length=200)),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "News",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("level", models.PositiveSmallIntegerField()),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="api.region",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="WelloPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_id", models.CharField(max_length=100, unique=True)),
                ("meta_policy_id_idx", models.CharField(blank=True, max_length=100)),
                ("agency_logo", models.URLField(blank=True)),
                ("policy_name", models.CharField(blank=True, max_length=200)),
                ("agency", models.CharField(max_length=100)),
                ("support_target", models.CharField(blank=True, max_length=255)),
                ("application_period", models.CharField(blank=True, max_length=100)),
                ("responsible_agency", models.CharField(blank=True, max_length=100)),
                ("support_benefit", models.CharField(blank=True, max_length=100)),
                ("like_count", models.IntegerField(default=0)),
                ("like_yn", models.BooleanField(default=False)),
                ("comment_count", models.IntegerField(default=0)),
                ("wishlist_yn", models.BooleanField(default=False)),
                ("expiration_date", models.CharField(max_length=50)),
                ("dday", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "regions",
                    models.ManyToManyField(related_name="policies", to="api.region"),
                ),
            ],
            options={
                "db_table": "wello_policies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="support",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "지원사업",
                "verbose_name_plural": "지원사업들",
            },
        ),
        migrations.AddField(
            model_name="support",
            name="benefit",
            field=models.TextField(default="", help_text="지원 내용"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="support",
            name="contact",
            field=models.CharField(blank=True, help_text="담당부서 연락처", max_length=100),
        ),
        migrations.AddField(
            model_name="support",
            name="how_to_apply",
            field=models.TextField(default="", help_text="신청 방법"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="support",
            name="organization",
            field=models.CharField(default="", help_text="주관 기관", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="support",
            name="region",
            field=models.CharField(blank=True, help_text="지원 가능 지역", max_length=100),
        ),
        migrations.AddField(
            model_name="support",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="support",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "진행중"), ("upcoming", "예정"), ("ended", "종료")],
                default="ongoing",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="support",
            name="support_type",
            field=models.CharField(
                choices=[
                    ("financial", "금전적 지원"),
                    ("medical", "의료 지원"),
                    ("adoption", "입양 지원"),
                    ("education", "교육 지원"),
                    ("other", "기타"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="support",
            name="target",
            field=models.TextField(default="", help_text="지원 대상"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="support",
            name="website_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="WelloPolicyDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.JSONField(null=True)),
                ("website_url", models.URLField(max_length=500, null=True)),
                ("contact_number", models.CharField(max_length=50, null=True)),
                ("target", models.TextField()),
                ("content", models.TextField()),
                ("related_info", models.TextField(null=True)),
                ("how_to_apply", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="api.wellopolicy",
                    ),
                ),
            ],
            options={
                "db_table": "wello_policy_details",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residents",
                to="api.region",
            ),
        ),
    ]
