# Generated by Django 4.2.19 on 2025-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_legalcode_news_region_wellopolicy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="support",
            name="agency_logo",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="support",
            name="expires_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="support",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="support",
            name="original_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="support",
            name="regions",
            field=models.ManyToManyField(
                blank=True, related_name="supports", to="api.region"
            ),
        ),
        migrations.AddField(
            model_name="support",
            name="source",
            field=models.CharField(
                choices=[("manual", "직접입력"), ("crawling", "크롤링"), ("news", "뉴스")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="support",
            name="summary",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
