# Generated by Django 4.2.16 on 2025-02-21 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_specialty_alter_pet_age_alter_pet_gender_and_more"),
        ("api", "0003_salon"),
    ]

    operations = []
