# Generated by Django 4.2.19 on 2025-04-08 04:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_support_agency_logo_support_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="support",
            options={
                "ordering": ["-expires_at"],
                "verbose_name": "지원사업",
                "verbose_name_plural": "지원사업들",
            },
        ),
    ]
