# Generated by Django 4.2.19 on 2025-04-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_support_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="support",
            name="latitude",
            field=models.FloatField(blank=True, help_text="위도", null=True),
        ),
        migrations.AddField(
            model_name="support",
            name="longitude",
            field=models.FloatField(blank=True, help_text="경도", null=True),
        ),
    ]
