# Generated by Django 4.2.19 on 2025-05-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_support_latitude_support_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="latitude",
            field=models.FloatField(blank=True, help_text="위도", null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="longitude",
            field=models.FloatField(blank=True, help_text="경도", null=True),
        ),
    ]
